os:
    - linux
    - osx
language: generic
sudo: required
dist: trusty

osx_image: xcode9.2
before_install:
    - if [ $TRAVIS_OS_NAME == "osx" ]; then
            brew tap vapor/tap;
            brew update;
            brew install vapor;
            brew install mongodb;
            sudo mkdir -p /data/db;
            brew services start mongodb;
        else
            eval "$(curl -sL https://apt.vapor.sh)";
            sudo apt-get install vapor;
            sudo chmod -R a+rx /usr/;
        fi

script:
    - swift build -c release
    - swift test

services:
  - mongodb
